package com.iyzipay.model.requesttopay.enumtype;

public enum PaymentPurpose {
    RESIDENTIAL_RENT,
    BUSINESS_RENT,
    OTHER_RENT,
    ECOMMERCE,
    SALARY,
    BUSINESS_PAYMENT,
    PENSION_PAYMENT,
    INVESTMENT,
    FINANCIAL,
    TUITION_PAYMENT,
    SUBSCRIPTION_FEE,
    REAL_ESTATE_PURCHASE,
    MOTOR_VEHICLE_PURCHASE,
    DEBT_PAYMENT,
    GIFT_DONATION,
    TAX_DUTY_FEE,
    COMPENSATION_INSURANCE,
    LEGAL_CONSULTANCY,
    HEALTH_PAYMENT,
    CRYPTO_DIGITAL_ASSET,
    LOTTERY_BETTING,
    ENTERTAINMENT_SOCIAL_MEDIA;
}